import QtQuick

QtObject {
    id: _root

    readonly property color primary: "#0052FF"
    readonly property color primaryForeground: "#FFFFFF"
    readonly property color accentSecondary: "#4D7CFF"
    readonly property color background: "#0F172A"
    readonly property color foreground: "#FAFAFA"
    readonly property color card: "#1E293B"
    readonly property color cardForeground: "#FAFAFA"
    readonly property color popover: "#1E293B"
    readonly property color popoverForeground: "#FAFAFA"
    readonly property color secondary: "#1E293B"
    readonly property color secondaryForeground: "#CBD5E1"
    readonly property color muted: "#334155"
    readonly property color mutedForeground: "#94A3B8"
    readonly property color accent: "#0052FF"
    readonly property color accentForeground: "#FFFFFF"
    readonly property color distructive: "#EF4444"
    readonly property color distructiveForeground: "#FFFFFF"
    readonly property color border: "#334155"
    readonly property color input: "#334155"
    readonly property color ring: "#0052FF"
    readonly property color chart1: "#0052FF"
    readonly property color chart2: "#4D7CFF"
    readonly property color chart3: "#64748B"
    readonly property color chart4: "#F1F5F9"
    readonly property color chart5: "#E2E8F0"

    readonly property color red100: "#FFE2E2"
    readonly property color red500: "#FB2C36"
    readonly property color orange50: "#FFF7ED"
    readonly property color orange500: "#FF6900"
    readonly property color orange600: "#F54900"
    readonly property color green50: "#F0FDF4"
    readonly property color green500: "#00C950"
    readonly property color green600: "#00A63E"
    readonly property color cyan400: "#00D3F2"
    readonly property color blue50: "#EFF6FF"
    readonly property color blue500: "#2B7FFF"
    readonly property color blue600: "#155DFC"
    readonly property color blue700: "#1447E6"
    readonly property color purple50: "#FAF5FF"
    readonly property color purple500: "#AD46FF"
    readonly property color purple600: "#9810FA"
    readonly property color slate50: "#F8FAFC"
    readonly property color slate100: "#F1F5F9"
    readonly property color slate600: "#45556C"
    readonly property color slate700: "#314158"
    readonly property color slate900: "#0F172B"
}
